[package]
name = "object_space"
version = "0.1.0"
authors = ["tmt <mt12@williams.edu>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
ordered-float = "0.5.0"
chashmap = "2.2.0"
indexmap = "1.0"

[dev-dependencies]
chrono = "0.4"
image = "0.18"
